env:
  browser: true
  es6: true
  jquery: true
extends:
  - airbnb
settings:
  react:
    version: latest
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-underscore-dangle: 0
